# Supervisor.start_child(IEx.Supervisor, {SSHConsole, %{ip: "127.0.0.1", port: 4022}})
# DynamicSupervisor.start_child(MyApp.Supervisor, {SSHConsole, %{ip: "127.0.0.1", port: 4022}})
defmodule SSHConsole do
  @moduledoc """
  Elixir console over OTP SSH, authenticated by the OS user's authorized_keys.
  Expressions run with the node's full authority. Module definitions are
  soft-purged before loading; busy modules are queued and retried. The BEAM
  keeps two code versions, so force-purging a third can kill running processes.
  The preflight covers literal top-level and directly nested definitions only;
  modules generated by macros or conditionals are outside that check.

  Listens on 127.0.0.1:4022 by default; pass %{ip: "0.0.0.0", port: 4023}
  to start_link/1 to bind all IPv4 interfaces on another port.
  Uses ~/.ssh/id_ed25519 as its server identity, generating the pair if absent.
  An encrypted private key raises at startup; OTP cannot load encrypted Ed25519 keys.
  Pass :user_dir to change the directory for both the identity and authorized_keys.
  """

  use GenServer

  @default_ip {127, 0, 0, 1}
  @default_port 4022
  @default_user_dir "~/.ssh"
  @retry_ms 50
  @source_name "ssh-console"
  @max_output_bytes 8 * 1024 * 1024

  def start_link(opts \\ %{}) do
    opts = Map.new(opts)
    GenServer.start_link(__MODULE__, opts, name: Map.get(opts, :name, __MODULE__))
  end

  @doc "Loads top-level modules, or queues the newest source until old code is unused."
  def hotload(source, opts \\ %{}) when is_binary(source) do
    opts = Map.new(opts)
    file = Map.get(opts, :file, @source_name)
    env = Map.get(opts, :env, Code.env_for_eval(file: file, line: 1))
    server = Map.get(opts, :server, __MODULE__)

    with {:ok, quoted} <- Code.string_to_quoted(source, file: file, line: 1),
         {:ok, modules} when modules != [] <- module_names(quoted, env) do
      GenServer.call(server, {:hotload, source, env, modules}, :infinity)
    else
      {:ok, []} -> {:error, :no_module_definition}
      {:error, _reason} = error -> error
    end
  end

  @doc false
  def module_names(quoted, %Macro.Env{} = env) do
    forms = block_forms(quoted)

    cond do
      Enum.all?(forms, &defmodule_call?/1) ->
        {:ok, forms |> Enum.flat_map(&collect_module_names(&1, env)) |> Enum.uniq()}

      Enum.any?(Macro.prewalker(quoted), &defmodule_call?/1) ->
        {:error, :module_definitions_must_be_top_level}

      true ->
        {:ok, []}
    end
  catch
    reason -> {:error, reason}
  end

  @doc false
  def shell(server \\ __MODULE__) do
    spawn(fn ->
      IO.puts("Elixir SSH console. Ctrl-C disconnects without stopping the node.")
      repl(%{server: server, binding: [], env: Code.env_for_eval(file: @source_name, line: 1),
        parser_state: [], source: "", counter: 1})
    end)
  end

  @doc false
  def exec(command, _user, _peer_address, server \\ __MODULE__) do
    source = IO.chardata_to_string(command)
    env = Code.env_for_eval(file: @source_name, line: 1)
    quoted = Code.string_to_quoted!(source, file: @source_name, line: 1)
    {status, output, _binding, _env} = evaluate(quoted, source, [], env, server)
    {status, output}
  catch
    kind, reason -> {:error, Exception.format(kind, reason, __STACKTRACE__)}
  end

  @impl true
  def init(opts) do
    Process.flag(:trap_exit, true)
    case start_daemon(opts) do
      {:ok, daemon_ref, address} ->
        Process.monitor(daemon_ref)
        IO.inspect {__MODULE__, :listening, address}
        {:ok, %{daemon_ref: daemon_ref, pending: [], retry_timer: nil}}

      {:error, reason} -> {:stop, reason}
    end
  end

  @impl true
  def handle_call({:hotload, source, env, modules}, _from, state) do
    job = %{source: source, env: env, modules: modules}
    pending = Enum.reject(state.pending, fn queued -> Enum.any?(queued.modules, &(&1 in modules)) end)

    case attempt_hotload(job) do
      {:busy, busy_modules} ->
        reply = %{
          status: :queued,
          modules: modules,
          waiting_for: busy_modules,
          blockers: blocker_info(busy_modules)
        }

        {:reply, {:ok, reply}, schedule_retry(%{state | pending: pending ++ [job]})}

      {:ok, _} = result -> {:reply, result, %{state | pending: pending}}
      error -> {:reply, error, state}
    end
  end

  @impl true
  def handle_info(:retry_hotloads, state) do
    pending = Enum.filter(state.pending, fn job ->
      case attempt_hotload(job) do
        {:busy, _} -> true
        result ->
          IO.inspect {__MODULE__, :hotload_retry, result}
          false
      end
    end)
    {:noreply, schedule_retry(%{state | pending: pending, retry_timer: nil})}
  end

  def handle_info({:DOWN, _ref, :process, daemon, reason}, %{daemon_ref: daemon} = state) do
    {:stop, {:ssh_daemon_down, reason}, %{state | daemon_ref: nil}}
  end

  def handle_info(_message, state), do: {:noreply, state}

  @impl true
  def terminate(_reason, %{daemon_ref: nil}), do: :ok

  def terminate(_reason, %{daemon_ref: daemon_ref}) do
    :ssh.stop_daemon(daemon_ref)
  catch
    :exit, _ -> :ok
  end

  defp repl(state) do
    prefix = if state.source == "", do: "ssh", else: "..."

    case IO.gets("#{prefix}(#{state.counter})> ") do
      :eof -> :ok
      {:error, reason} -> IO.puts("console input failed: #{inspect(reason)}")
      line -> repl(eval_line(IO.chardata_to_string(line), state))
    end
  end

  defp eval_line(line, state) do
    source = state.source <> line
    parser_opts = [file: @source_name, line: state.counter, column: 1]

    case IEx.Evaluator.parse(String.to_charlist(line), parser_opts, state.parser_state) do
      {:incomplete, parser_state} ->
        %{state | parser_state: parser_state, source: source}

      {:ok, quoted, parser_state} ->
        # Elixir 1.20 returns a parser callback; earlier releases return the AST.
        quoted = if is_function(quoted, 0), do: quoted.(), else: quoted
        {_status, output, binding, env} = evaluate(quoted, source, state.binding, state.env, Map.get(state, :server, __MODULE__))
        IO.puts(output)
        %{state | binding: binding, env: env, parser_state: parser_state, source: "", counter: state.counter + 1}
    end
  catch
    kind, reason ->
      IO.puts(Exception.format(kind, reason, __STACKTRACE__))
      %{state | parser_state: [], source: "", counter: state.counter + 1}
  end

  defp evaluate(quoted, source, binding, env, server) do
    case module_names(quoted, env) do
      {:ok, []} ->
        {value, binding, env} = Code.eval_quoted_with_env(quoted, binding, env)
        {:ok, inspect_value(value), binding, env}

      {:ok, modules} ->
        case GenServer.call(server, {:hotload, source, env, modules}, :infinity) do
          {:ok, result} -> {:ok, inspect_value(result), binding, env}
          {:error, reason} -> {:error, inspect(reason), binding, env}
        end

      {:error, reason} ->
        {:error, "hotload rejected: #{inspect(reason)}", binding, env}
    end
  catch
    kind, reason -> {:error, Exception.format(kind, reason, __STACKTRACE__), binding, env}
  end

  defp start_daemon(opts) do
    server = self()
    with {:ok, _apps} <- Application.ensure_all_started(:ssh),
         {:ok, _apps} <- Application.ensure_all_started(:iex),
         {:ok, ip} <- console_ip(opts),
         {:ok, port} <- console_port(opts),
         {:ok, key_opts} <- prepare_keys(opts) do
      daemon_opts = [
        # Post-quantum only: hybrid ML-KEM-768 + X25519 (OTP 29 / ssh 6.0) is the
        # sole kex offered, so a client cannot downgrade to a classical exchange;
        # ed25519 host key, AEAD ciphers, encrypt-then-mac. OpenSSH >= 9.9 needed.
        preferred_algorithms: [
          kex: [:"mlkem768x25519-sha256"],
          public_key: [:"ssh-ed25519"],
          cipher: [:"aes256-gcm@openssh.com", :"chacha20-poly1305@openssh.com"],
          mac: [:"hmac-sha2-512-etm@openssh.com", :"hmac-sha2-256-etm@openssh.com"]
        ],
        auth_methods: ~c"publickey",
        shell: {__MODULE__, :shell, [server]},
        exec: {:direct, fn command, user, peer -> __MODULE__.exec(command, user, peer, server) end},
        subsystems: [],
        tcpip_tunnel_in: false,
        tcpip_tunnel_out: false,
        connectfun: fn user, peer, method -> IO.inspect {__MODULE__, :login, user, peer, method} end,
        failfun: fn user, peer, reason -> IO.inspect {__MODULE__, :rejected, user, peer, reason} end
      ]

      case :ssh.daemon(ip, port, daemon_opts ++ key_opts) do
        {:ok, daemon_ref} -> {:ok, daemon_ref, "#{:inet.ntoa(ip)}:#{port}"}
        {:error, reason} -> {:error, {:ssh_daemon, reason}}
      end
    end
  end

  defp attempt_hotload(job) do
    case Enum.reject(job.modules, &:code.soft_purge/1) do
      [] ->
        Code.eval_string(job.source, [], job.env)
        {:ok, %{
          status: :loaded,
          modules: job.modules,
          loaded_at_ms: :os.system_time(:millisecond),
          module_md5: Map.new(job.modules, &{&1, module_md5(&1)})
        }}

      busy -> {:busy, busy}
    end
  catch
    kind, reason -> {:error, {:compile, Exception.format(kind, reason, __STACKTRACE__)}}
  end

  defp schedule_retry(%{pending: []} = state), do: state
  defp schedule_retry(%{retry_timer: timer} = state) when is_reference(timer), do: state

  defp schedule_retry(state) do
    %{state | retry_timer: Process.send_after(self(), :retry_hotloads, @retry_ms)}
  end

  defp blocker_info(modules) do
    pids = Process.list()
    for module <- modules, pid <- pids, :erlang.check_process_code(pid, module) do
      info = Process.info(pid, [:registered_name, :current_function, :message_queue_len]) || []
      %{module: module, pid: pid, process: Map.new(info)}
    end
  end

  defp module_md5(module) do
    module.module_info(:md5)
    |> Base.encode16(case: :lower)
  rescue
    _error -> nil
  end

  defp collect_module_names({:defmodule, _meta, [name_ast, body]}, env) do
    module = expand_defmodule_name(name_ast, env)

    if not is_atom(module), do: throw({:dynamic_module_name, Macro.to_string(name_ast)})

    nested = body |> Keyword.get(:do) |> block_forms() |> Enum.filter(&defmodule_call?/1)
    [module | Enum.flat_map(nested, &collect_module_names(&1, %{env | module: module}))]
  end

  defp collect_module_names(_other, _env), do: throw(:invalid_module_definition)

  defp expand_defmodule_name({:__aliases__, _meta, [:Elixir | parts]}, _env) do
    Module.concat(parts)
  end

  defp expand_defmodule_name({:__aliases__, _meta, parts}, %{module: module})
       when is_atom(module) and not is_nil(module) do
    Module.concat([module | parts])
  end

  defp expand_defmodule_name(name_ast, env), do: Macro.expand(name_ast, env)

  defp defmodule_call?({:defmodule, _meta, [_name, body]}) when is_list(body), do: true
  defp defmodule_call?(_other), do: false

  defp block_forms({:__block__, _meta, forms}), do: forms
  defp block_forms(nil), do: []
  defp block_forms(form), do: [form]

  defp console_ip(opts) do
    value = Map.get(opts, :ip, @default_ip)
    parsed = if is_binary(value) or is_list(value), do: :inet.parse_ipv4_address(to_charlist(value)), else: {:ok, value}

    with {:ok, ip} <- parsed, true <- :inet.is_ipv4_address(ip) do
      {:ok, ip}
    else
      _ -> {:error, {:invalid_ssh_console_ip, value}}
    end
  end

  defp console_port(opts) do
    value = Map.get(opts, :port, @default_port)
    parsed = if is_binary(value), do: Integer.parse(value), else: {value, ""}

    case parsed do
      {port, ""} when is_integer(port) and port in 1..65_535 -> {:ok, port}
      _ -> {:error, {:invalid_ssh_console_port, value}}
    end
  end

  defp inspect_value(value) do
    output = inspect(value, pretty: true, limit: 1_000_000, printable_limit: @max_output_bytes)

    if byte_size(output) > @max_output_bytes do
      binary_part(output, 0, @max_output_bytes) <> "\n...(truncated at 8MB)"
    else
      output
    end
  end

  #### SSHConsole Keys

  defp prepare_keys(opts) do
    with {:ok, path} <- authorized_keys_path(opts),
         {:ok, user} <- local_user(opts) do
      key_opts = [
        user_dir: path |> Path.dirname() |> String.to_charlist(),
        key_cb: {__MODULE__, [user: user, path: path]}
      ]
      # Check outside :ssh.daemon: OTP swallows key callback exceptions.
      with {:ok, _key} <- host_key(:"ssh-ed25519", key_opts), do: {:ok, key_opts}
    end
  end

  def host_key(:"ssh-ed25519" = algorithm, opts) do
    path = Path.join(Keyword.fetch!(opts, :user_dir), "id_ed25519")
    with :ok <- generate_host_key(path),
         :ok <- reject_encrypted_key!(path),
         :ok <- File.chmod(path, 0o600),
         {:ok, key} <- :ssh_file.user_key(algorithm, opts),
         :ok <- ensure_public_key(path <> ".pub", key) do
      {:ok, key}
    else
      {:error, reason} -> {:error, {:ssh_host_key, reason}}
    end
  end

  def host_key(_algorithm, _opts), do: {:error, :unsupported_host_key_algorithm}

  defp reject_encrypted_key!(path) do
    with {:ok, contents} <- File.read(path) do
      if encrypted_key?(contents), do: raise("SSHConsole private key is encrypted: #{path}")
      :ok
    end
  end

  defp encrypted_key?(contents) do
    Enum.any?(:public_key.pem_decode(contents), fn
      {_, <<"openssh-key-v1", 0, size::32, cipher::binary-size(size), _::binary>>, _} -> cipher != "none"
      {_, _, encryption} -> encryption != :not_encrypted
    end)
  catch
    _, _ -> false # Leave malformed keys to OTP's key loader.
  end

  def is_auth_key(key, user, opts) do
    %{user: allowed_user, path: path} = Map.new(Keyword.fetch!(opts, :key_cb_private))
    IO.chardata_to_string(user) == allowed_user and
      MapSet.member?(cached_keys(path), key)
  catch
    _, _ -> false
  end

  defp authorized_keys_path(opts) do
    dir = Map.get(opts, :user_dir, @default_user_dir)
    if is_binary(dir) do
      path = Path.join(Path.expand(dir), "authorized_keys")
      if MapSet.size(cached_keys(path)) > 0, do: {:ok, path}, else: {:error, {:no_authorized_keys, [path]}}
    else
      {:error, {:invalid_user_dir, dir}}
    end
  end

  defp cached_keys(path) do
    cache = {__MODULE__, :authorized_keys, path}
    now = :os.system_time(:millisecond)
    with {:ok, stamp} <- key_stamp(path) do
      case :persistent_term.get(cache, nil) do
        {^stamp, keys} when stamp.mtime + 1_000 <= now and stamp.ctime + 1_000 <= now -> keys
        _ ->
          with {:ok, contents} <- File.read(path), {:ok, ^stamp} <- key_stamp(path) do
            keys = contents |> String.split("\n") |> Enum.flat_map(&decode_key_line/1) |> MapSet.new()
            # OTP stat timestamps have second precision. Never cache a snapshot from
            # the current second: another same-size edit could have identical metadata.
            if max(stamp.mtime, stamp.ctime) + 1_000 <= now do
              :persistent_term.put(cache, {stamp, keys})
            else
              :persistent_term.erase(cache)
            end
            keys
          else
            _ -> clear_keys(cache)
          end
      end
    else
      _ -> clear_keys(cache)
    end
  end

  defp clear_keys(cache) do
    :persistent_term.erase(cache)
    MapSet.new()
  end

  defp key_stamp(path) do
    with {:ok, %{type: :regular, access: access} = s} when access in [:read, :read_write] <- File.stat(path, time: :posix) do
      {:ok, %{mtime: s.mtime * 1_000, ctime: s.ctime * 1_000, size: s.size,
        inode: s.inode, device: {s.major_device, s.minor_device}, mode: s.mode, uid: s.uid, gid: s.gid}}
    else
      _ -> {:error, :unreadable_authorized_keys}
    end
  end

  defp decode_key_line(line) do
    line = String.trim(line)
    if String.starts_with?(line, "#"), do: [], else: Enum.map(:ssh_file.decode(line, :auth_keys), &elem(&1, 0))
  catch
    _, _ -> []
  end

  defp local_user(opts) do
    user = Map.get_lazy(opts, :user, fn ->
      {name, 0} = System.cmd("id", ["-un"])
      String.trim(name)
    end)

    if is_binary(user) and user != "", do: {:ok, user}, else: {:error, :missing_local_user}
  catch
    kind, reason -> {:error, {:local_user, kind, reason}}
  end

  defp ensure_public_key(path, key) do
    if File.exists?(path) do
      :ok
    else
      public = :ssh_file.extract_public_key(key)
      File.write(path, :ssh_file.encode([{public, []}], :openssh_key), [:exclusive])
    end
  end

  defp generate_host_key(private_key) do
    cond do
      File.regular?(private_key) -> :ok
      File.exists?(private_key) -> {:error, :invalid_private_key}
      File.exists?(private_key <> ".pub") -> {:error, :missing_private_key}
      true ->
        case System.find_executable("ssh-keygen") do
          nil -> {:error, :ssh_keygen_not_found}
          executable ->
            args = ["-q", "-t", "ed25519", "-N", "", "-f", private_key]
            case System.cmd(executable, args, stderr_to_stdout: true) do
              {_output, 0} -> :ok
              {output, status} -> {:error, {:ssh_keygen_failed, status, output}}
            end
        end
    end
  end
end
